### ISSUE TITLE
Failed to create Sesame repository

### ISSUE THREAD

**Issue by gigialmo88** [chrpin/rodi#1]
Hi,

I updated the maven dependency for slf4j-log4j12 to this updated version since it was giving an error regarding the 1.7.4 version:

<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-log4j12</artifactId>
    <version>1.7.21</version>
</dependency>

After running the main.java I received this error:

BENCHMARK: preparing scenario cmt_renamed
Cleaning possible mappings from previous scenarios...
Loading SQL dump into database...
RDBMS set to default (PostgreSQL).
done.
Loading RDF data...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/PeachyJoKiller88/.m2/repository/org/slf4j/slf4j-simple/1.6.1/slf4j-simple-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/PeachyJoKiller88/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
24 [main] WARN org.openrdf.sail.memory.MemoryStore - Failed to lock directory: .\sesame_db\main
Exception in thread "main" java.lang.RuntimeException: Failed to create Sesame repository as writable, backed up on ./sesame_db/main/. Full reset may be required.
    at com.fluidops.rdb2rdfbench.db.rdf.SesameAdapter.<init>(SesameAdapter.java:92)
    at com.fluidops.rdb2rdfbench.db.rdf.SesameAdapter.reset(SesameAdapter.java:143)
    at com.fluidops.rdb2rdfbench.util.SetupUtil.setupScenario(SetupUtil.java:44)
    at com.fluidops.rdb2rdfbench.eval.Evaluator.automaticWorkflow(Evaluator.java:537)
    at com.fluidops.rdb2rdfbench.Main.main(Main.java:249)

Any help or suggestions would be appreciated. Thanks!

**Comment by chrpin** [comment]
I will take a look at the logger versions shortly, but these messages read like warnings, only (as far as logging is concerned).

The error that kills your process appears to be unrelated ('Exception in thread "main"' etc.): the triple store could not be initialized. Please make sure that all the sub directories in your RODI folder are fully writable, then try --setup again. If that shouldn't help, try to remove ./sesame_db/main and create it as an empty folder.

**Comment by gigialmo88** [comment]
I am using windows 8 and running the source code through eclipse so the directories should be writable. I removed the sesame_db/main folder, but I don't understand what you mean by create it as an empty folder? I executed it again, and I still receive the same error as before. I'm fairly new to this so I appreciate your patience!

**Comment by chrpin** [comment]
Well, this should really work. The issue also originates from the Sesame triples store (http://rdf4j.org), and our own wrapping code around it looks rather innocent. Note, however, that none of us is using Windows, and while we performed one (successful) dry-run of the benchmark before the release, no other testing in Windows file environments did happen.

Things to try:
- To be on the safe side, the sesame_db/main directory should exist, just as a fresh, newly created directory with nothing in it (and no other applications using it)
- Check your configuration: Windows path names may require double backslashes in the encoding of the path (i.e., c:\some\path instead of just c:\some\path). Also, try using regular slashes instead of backslashes.
- A fully qualified path name (c:\your_path\...) could also be worth a try.
- If you are familiar with Java, set a breakpoint at SesameAdapter.java:92 and check the state of backupDir (Does it point to the right directory?)

The only two reasons for this behavior that I could figure are (1) that the backupDir object does not point to the correct path in your environment, or (2) the directory still contains some files/locks from a previous, unsuccessful attempt to initialize the DB backup file.

Edit: nb. Windows testing was done with the pre-compiled package available from Uni Oxford (https://www.cs.ox.ac.uk/isg/tools/RODI/). Maybe you would like to use this instead of your own maven compile and check if the error persists.

**Comment by gigialmo88** [comment]
Well for some reason, I ran the code again, and this time there were no error messages. But it displays this now:

BENCHMARK: preparing scenario cmt_renamed
Cleaning possible mappings from previous scenarios...
Loading SQL dump into database...
RDBMS set to default (PostgreSQL).
done.
Loading RDF data...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/PeachyJoKiller88/.m2/repository/org/slf4j/slf4j-simple/1.6.1/slf4j-simple-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/PeachyJoKiller88/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
52 [main] WARN org.openrdf.sail.helpers.DirectoryLockManager - Removing invalid lock 1936@PeachyJoKiller
20341 [main] WARN org.openrdf.sail.memory.MemoryStore - Closing active connection due to shut down; consider setting the org.openrdf.repository.debug system property
20345 [main] WARN org.openrdf.sail.helpers.DirectoryLockManager - Removing invalid lock 1936@PeachyJoKiller
40398 [main] WARN org.openrdf.sail.memory.MemoryStore - Closing active connection due to shut down; consider setting the org.openrdf.repository.debug system property
Transferring base copy of data into evaluation repository...
BENCHMARK: scenario ready: cmt_renamed
BENCHMARK: now waiting for R2RML to be submitted...

And it just stays like forever until I terminate it. I don't know if this is a step in the right direction or not? I checked and the backupDir is correct. Also, I am using the pre-compiled package from the site you provided.

**Comment by chrpin** [comment]
Okay, except for some of the warnings (which are not critical at all), this is expected behavior. So yes, the software is now working fine for you.

RODI supports different modes of operations that require different command line parameters when invoked and expect different kind of input at different stages (in your case, the framework is busy-waiting for a mapping generator to submit its solution). Please refer to our manual (linked from the front page) for details. If you expect a different behavior, I suspect that you would need to apply RODI in a different mode (e.g., using --setup --scenario="name_the_scenario" first, and later using --eval --scenario="...", but there are other alternatives that should all become clear after reading the manual).

In any case, what's left here is a support matter, not a software issue. Please feel free to contact either myself or one of my collaborators directly for support if the manual should not be sufficiently clear to you. Contact e-mails are linked from the University of Oxford web page for RODI (direct link above in this thread).
